databases:
  - name: Blossoms
    databaseName: blossoms_6mh9
    user: blossoms_6mh9_user
    
services:
  - type: web
    name: evergreen
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: blossoms_6mh9
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
        